@startuml
'https://plantuml.com/class-diagram
class Cliente {
    - id: int
    - nome: String
    - cpf: String
}

class Relatorio {
    + imprimir(cliente: Cliente): String
}

class Venda {
    - id: int
    - data: String
    - valor: double
}

class CupomFiscal {
    + imprimir(venda: Venda): String
}

enum Situacao {
    ABERTA
    FINALIZADA
    CANCELADA
}

Venda --> "1" Cliente
Venda --> Situacao
Relatorio ..> Cliente
CupomFiscal ..> Venda

@enduml